### ISSUE TITLE
Please support scanning the portage tree/kits of ebuilds

### ISSUE THREAD

**Issue by seemantk** [mrl5/vulner#29]
Hello Jakub.  `vulner` is very useful in its current state to understand the installed packages.

From the perspective of a Linux distro maintainer, I want to use `vulner` to check all the available packages for vulnerabilities so that we can proactively solve them , instead of waiting for users to run `vulner` and report issues.

**Comment by mrl5** [comment]
after some discord discussion this CLI design looks most promising:
```bash
vulner scan --recursive -p /var/git/meta-repo
vulner scan -p /var/git/meta-repo/kits/core-kit
```

**Comment by mrl5** [comment]
`vulner scan --recursive -p /var/git/meta-rep` part will be delivered in following commit
